### PR TITLE
Changed if construct of water feature and added a bit more :D

### PR DESCRIPTION
**Pull request by mukunddeepak**
Contributing towards issue number #32 
The bit more part might not be necessary but still......

### CODE REVIEW

**Comment by mukunddeepak** [comment]
Added help and contrib as a part of water.js. Simplified!

**Review by srujandeshpande — APPROVED** [review]
Looks great and is a much-needed cleanup.

**Comment by srujandeshpande** [comment]
@mukunddeepak There is a small update we can possibly do since we're in this file already
Remove the `Block for possible future direct issue creation` comment block since it isn't going to be used anytime soon

**Comment by mukunddeepak** [comment]
Sure! On it!

**Comment by mukunddeepak** [comment]
Done with the changes! Merge and close it.

**Review by srujandeshpande — APPROVED** [review]
lgtm

**Pull request merged**
