### PR TITLE
Add interactions and migrate to discord.js V13

### PR DESCRIPTION
**Pull request by Omicron02**
* Commands beginning with the `water` prefix now have corresponding slash commands. 
* Created a new folder `intrcommands` containing files to facilitate slash commands.
* Discord.js version updated to v13 to in order to properly utilise slash commands. 
* Altered existing code to remove deprecated syntax. 
* Global slash command registration included.
* help.js still references docstrings from the original command files.

### CODE REVIEW

**Comment by Omicron02** [comment]
Apologies for any crappy code, I'm pretty new to discord bot stuff.

**Comment by ArnavKumar7** [comment]
can you tell me how you tested the bot?

**Comment by Omicron02** [comment]
> tell
The details were available in CONTRIBUTIONS.md

**Comment by Omicron02** [comment]
Made the requested changes

**Comment by ArnavKumar7** [comment]
!bounty 165

**Pull request closed without merging**
